cmd/junod/cmd/airdrop.go

Changed osmos references to juno

Changed osmosis references to juno

---

app/prefix.go
cmd/junod/cmd/airdrop.go
cmd/junod/cmd/root.go

add command to root
add args for poll

airdrop command work

---

app/app.go
x/mint/client/cli/query.go
x/mint/client/rest/grpc_query_test.go
x/mint/client/testutil/cli_test.go
x/mint/client/testutil/suite.go
x/mint/module.go
x/mint/simulation/decoder.go
x/mint/spec/02_state.md
x/mint/types/minter_test.go

pending changes from https://github.com/faddat/Juno-1/pull/2  .

Mint 0.43 updates

---

app/app.go

Fix error:
```
panic: router sealed; cannot add route handler
```

Fix register wasm proposals

---

app/app.go

- Add ibc router
- Add burn permission https://github.com/CosmWasm/wasmd/pull/489

Wasm ibc router

---

app/app.go

I tested upgrade plan, i uploaded wasm files (successful Tx) but command `junod q wasm codes` didn't give results .
`storeUpgrades` fixes the issue.
Reference 
- [cosmos-sdk documentation](https://docs.cosmos.network/master/core/upgrade.html#add-storeupgrades-for-new-modules)
- [gaia/app.go](https://github.com/cosmos/gaia/blob/0dc6e1b4b51ce31af6de1b218336dc05bb87ff58/app/app.go#L579)

Add storeUpgrades for new modules

---

app/app.go

fix wasmKeeper no initialized on gov route register.

Fix register wasm gov router

---

.github/workflows/docker.yml

Addresses #98 
This should improve tagging to use the git tags. For some reason it's not triggering the PR CI though. Hate testing GH actions.

Improve tagging

---

app/wasm_config.go

Will drop a note in TG about this.

10x compile cost again

---

app/wasm_config.go

WIP - currently testing locally but want the docker image created by the PR

Change compile cost again

---

.github/workflows/integration.yml
Dockerfile
app/app.go
go.mod
go.sum

WIP on this as it's late here.
Creating a PR so I can use the docker builds for further testing.
Builds and passes CI but needs further testing.

Use mainline wasmd

---

app/app.go

As pointed out by @giansalex it was possible to statesync past the moneta handler.
This catches validators that might have tried to dodge the handler - although it should be noted that it looks like none have tried to do so/been able to do so on mainnet.

Add forced commission update to lupercalia

---

.github/workflows/docker.yml
.github/workflows/integration.yml
Dockerfile
docker-compose.yml

I think we probably jumped the gun on ripping this all out and want to restore it ASAP.
Will probably need a few tries to get everything working again.

Reinstate dockerfile

---

.github/workflows/build.yml

It was recommended we add a tidy action to check deps. This should work, but might need a future iteration.

Spike tidy CI action

---

app/app.go
app/test_helpers.go
app/upgrade/constants.go
app/upgrade/upgrade_handler.go
app/upgrade/upgrade_test.go
x/mint/client/rest/grpc_query_test.go
x/mint/client/testutil/cli_test.go

V4.0.0 Unity

---

app/upgrade/upgrade_handler.go

Removing gun aimed directly at foot.
https://twitter.com/buchmanster/status/1522300607465414661
tested successfully on [ `scottie-3` testnet ](https://github.com/CosmosContracts/testnets/tree/main/scottie-3)

Follow Bucky's Advice

---

app/app.go
go.mod

This PR supercedes #215 and seeks to only integrate ICA Host functionality, rather than ICA Controller as well.

Integrate ICA Host Functionality

---

.github/workflows/superlinter.yml

this includes the tooling used by @joeabbey to tighten up our bash

superlinter

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/issue.md

Close #310
Add issue template, refer to osmosis and gaia templates.

Issue template

---

go.mod
go.sum

iavl v0.19.4

---

go.mod

This PR annotates go.mod for clarity.

annotate go.mod

---

RELEASES.md
SECURITY.md
x/mint/spec/01_concepts.md
x/mint/spec/02_state.md
x/mint/spec/03_begin_block.md
x/mint/spec/README.md

This PR runs
`markdownlint . --fix`

markdownlint

---

x/feeshare/keeper/msg_server.go

fix logic updateFeeShare

---

app/upgrades/v12/upgrades.go

Adds:
- TokenFactory
- FeeShare
and updates native modules new messages.

v12 - Upgrade More ICA messages

---

go.mod
go.sum

This PR bumps the gaia dependency, and should be merged asap because there 
are some issues with conflicting protobufs types (I think)

bump gaia dependency

---

.github/workflows/test-e2e-oracle.yml
.gitignore
Makefile
price-feeder/Makefile
price-feeder/go.mod
price-feeder/price-feeder.Dockerfile
tests/e2e/config.toml
tests/e2e/configurer/base.go
tests/e2e/configurer/chain/queries.go
tests/e2e/configurer/current.go
tests/e2e/configurer/factory.go
tests/e2e/configurer/setup.go
tests/e2e/containers/config.go
tests/e2e/containers/containers.go
tests/e2e/e2e_setup_test.go
tests/e2e/e2e_test.go
tests/e2e/initialization/Dockerfile
tests/e2e/initialization/init.Dockerfile
tests/e2e/scripts/init_config.sh

Add E2E-Test for Oracle and Price-feeder

---

RELEASES.md
ROADMAP.md
readme.md

Closes: #482 
Adds a roadmap & links for v12 and planned v13
Also fixed some minor spelling in the other markdown files

Future Roadmap (v12 & v13 planned)

---

app/keepers/keepers.go

Add more stargate queries for oracle

More stargate query

---

go.mod
go.sum

This PR fixes a vuln in jwt-go, which is no longer updated

fix jwt vuln

---

.github/workflows/release.yml

Closes #476 
Adds sha256sum output to text file
Use non deprecated release action with write-all permission
Proof:
- https://github.com/Reecepbcups/juno/releases

feat(release): Add sha256 sum

---

go.mod
go.sum

This PR ensures that Juno is safe from the odd behavior occuring at 
tendermint/tendermint.

use informal tendermint with sadness

---

.github/workflows/push-docker-images.yml

Docker: lowercase cosmoscontracts name

---

app/ante.go
app/app.go
app/decorators/constant.go
app/decorators/gov_filter.go

not enough:
```bash
junod tx gov submit-proposal software-upgrade example --title "ante test" --description "fails" --upgrade-height 1000 --keyring-backend test --chain-id juno-t1 --node http://localhost:26657 --from juno1
confirm transaction before signing and broadcasting [y/N]: y
code: 4
codespace: sdk
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'not enough initial deposit. required: 200000ujuno: unauthorized'
timestamp: ""
tx: null
txhash: 849B631CF970FF5A1F368AC3F9E1DDAD0B687CD70706B5A263EE5A79908CC039
```
success:
```bash
junod tx gov submit-proposal software-upgrade example --title "ante test" --description "success" --upgrade-height 1000 --keyring-backend test --chain-id juno-t1 --node http://localhost:26657 --from juno1 --deposit …
```

adds gov deposit handler to v12

---

app/upgrades/v13/constants.go
go.mod
go.sum

- Add icacontroller to store.StoreUpgrades

Missing ICA upgrade in store.StoreUpgrades

---

.github/workflows/interchaintest-E2E.yml

testing here so I do not get rate limited in other branch

Cache deps

---

go.mod
go.sum

[v14] version bumps

---

readme.md

This PR fixes bold text in the readme file.

fix bolding in readme

---

.github/CODEOWNERS

He will also need write access to the repo if not already

Adds justin (SL) as interchaintest/ codeowner

---

readme.md

this pull request adds attributions for major components of juno.

attribution

---

docker/run_junod.sh
docker/setup_junod.sh

- add genesis subcommand in docker container shell script while staking an amount and collecting gentxs

fix: add genesis subcommand and gas prices for local docker

---

app/export.go

Closes #778 
Pulled from simapp directly. backporting to v16 as well

fix: exports not working (SDK v47)

---

x/globalfee/ante/fee.go

Um what...
I pushed 27301e604f35d769b77892aea2cdfbd942958752 up. It is in the branch [reece/pretty-globalfee](https://github.com/CosmosContracts/juno/commits/reece/pretty-globalfee), but the PR #809 did not actually capture it. 
Really confused how that could have happened. Juno broke GH lol

Fix: Prettier GlobalFee commit error

---

x/clock/spec/02_integration.md

Update Clock 02_integration.md msg

---

app/upgrades/v17/upgrades.go

Closes #829
Since this only runs on mainnet, there would be no way to test on Uni.
Future test case for LocalIC
---
Local Test Upgrade (example contract proof)
Logic used
```sh
FILE_LOC=/home/reece/Desktop/blockchain_scripts/contracts/cw_template.wasm
$OLDBINARY tx wasm store $FILE_LOC --from $KEY --gas 1000000 --chain-id $CHAINID --yes --keyring-backend $KEYRING --node $NODE
CODE_ID=1
txhash=`$OLDBINARY tx wasm instantiate $CODE_ID '{"count":0}' --from $KEY --gas 1000000 --chain-id $CHAINID --yes --keyring-backend $KEYRING --node $NODE --label="cw_template" --admin=juno1jv65s3grqf6v6jl3dp4t6c9t9rk99cd83d88wr --output=json | jq -r .txhash`
contract_address=`$OLDBINARY q tx $txhash --node $NODE --output=json | jq -r .logs[0].events[1].attributes[0].value` && echo $contract_address …
```

v17: Migrate SubDAOs from distribution module -> gov

---

app/upgrades/v17/constants.go
app/upgrades/v17/upgrade_test.go
app/upgrades/v17/upgrades.go

Updated the v17 Upgrade Package name from `v16` to `v17`.

Fix v17 Upgrade Package Name

---

app/app.go
app/keepers/keepers.go
app/upgrades/v17/upgrades.go
go.mod
go.sum
x/clock/keeper/keeper.go
x/cw-hooks/keeper/keeper.go

- minor tweaks
- pigeonfall
- more IBC bypasses

v18 Cleanup

---

go.mod
go.sum
interchaintest/go.mod
interchaintest/go.sum

add MacOS ledger support. not required for vals to run

fix: ledger-cosmos-go v0.12.4

---

scripts/test_node.sh

minor but I keep having issues with it, so is a pain

fix: test_node fix voting period

---

app/app.go
app/keepers/keepers.go
app/upgrades/v19/upgrade_test.go
interchaintest/chain_upgrade_test.go
interchaintest/conformance/cosmwasm.go

This PR applies the v20.0.0 patch to the main branch.

fix! WasmVM Not Loading Contracts

---

app/app.go
app/keepers/keepers.go
app/upgrades/v13/upgrades.go
app/upgrades/v21/constants.go

lint the lints

---

app/keepers/keepers.go

credit: Luca @ Informal systems

patch!: IBC module ordering to allow for ICS29 relaying

---

.github/workflows/release.yml

fix docker binary copy
