cmd/junod/cmd/airdrop.go, cmd/junod/cmd/root.go, readme.md
Procedure
- Export snapshot with `junod export-airdrop-snapshot [airdrop-to-denom] [input-genesis-file] [input-exchange-addresses] [output-snapshot-json] --juno-supply=[juno-genesis-supply]`
- Init genesis with `junod init <moniker> --chain-id juno-1` 
- Import airdrop accounts with `add-airdrop-accounts [airdrop-snapshot-file] [denom]`
- Fix other parameters by hand (genesis time, other accounts, gentxs.. )
=> Add airdrop accounts command

app/app.go
Allow ibc-related functionality.
Error message:
```
Execute error: Error when broadcasting tx 8DC6EB1ECE54CA9EA603AFD1209FF6D5CCB231A630836C8CAB476582FCF5234D at 
height 694256. Code: 2; Raw log: failed to execute message; message index: 0: Error calling the VM: Error during static Wasm 
validation: Wasm contract requires unsupported features: {"stargate"}: create wasm contract failed
```
=> Enable stargate feature

docker/run_junod.sh, docker/setup_junod.sh
Juno default homepath is `"$HOME"/.juno/`
https://github.com/CosmosContracts/Juno/blob/1af28c37ef1c0fe3985a4006ca94f093f4f35f1b/app/app.go#L193
=> Fix Juno home in docker setup script

go.mod, go.sum
[ibc-go@v1.1.0](https://github.com/cosmos/ibc-go/releases/tag/v1.1.0) : `v1.0.x` is discontinued
=> Latest ibc-go v1.1.0

app/app.go, custom/auth/client/rest/broadcast.go, custom/auth/client/rest/rest.go
This PR add a custom `/txs` post endpoint to Legacy REST API that was removed by Cosmos-SDK v0.44. Since a lot of wallets still rely on that for transaction broadcasting we prefer to keep it for now.
Multisig + sequence security vulnerability should not affect this change
Specs for the custom endpoint
```typescript
{
"tx": StdTx,
"mode": "block" | "sync" | "async",
// Below fields are newly introduced optional arguments.
// To convert legacy tx to new proto tx, we need each signer's sequence number. 
// If this field is not given, we fetch the sequence from the chain state. Normal 
// users can skip this field as well, but the users who are sending faster than block 
// time need to provide this field.
"sequences": ["1", "2"],
"fee_granter": "",
"timeout_height": "10"
}
```
=> add custom /txs endpoint for wallet providers

app/app.go
Add an upgrade handler for moneta alpha. Somehow got missed before.
After this is merged, app should be tagged `v2.0.0-alpha.2` and instructions updated/uni testnet validators informed.
=> Add upgrade handler

cmd/junod/main.go
During the uni testnet, the upgrade from `v1.0.0` was targetting `v2.0.0-alpha.1`, and shortly thereafter `v2.0.0-alpha.2`.  The upgrade then needed one more fix and many participants were unaware that a `v2.0.0-alpha.3` was prepared.  As such, the normal network upgrade began to splinter into a few variants and seized for about 30 minutes.  Once a sufficient number of validators upgraded to `v2.0.0-alpha.3`, the network resumed producing blocks.
About 20 minutes later, at block 250,489, a wrong `Block.Header.AppHash` began to circulate through a few validators. From the `#validators-testnet` channel on Juno discord:
*siriska*:
https://discord.com/channels/816256689078403103/898335064465743963/904725667353088020
*jabbey*
https://discord.com/channels/816256689078403103/898335064465743963/90 …
=> Adding rollback to Juno CLI to workaround AppHash mismatches

.gitignore, app/ante.go, app/app.go
Upgrade handler in the vein of osmo solution, ante fix ported from stargaze.
Attempt to close off #17 so that we can test and ship with moneta.
Needs tagging as `v2.0.0-beta` if/when approved.
=> Validator minimum commission

SECURITY.md, readme.md
As per the suggestion of Alex at Confio, suggest a formalised process for features and issue disclosure. 
Now we have a process via the project board, this seems like a logical step to triage and formalise people coming to us.
=> Add security contact info

docker/setup_junod.sh
default keyring-backend is different for `keys add` and `add-genesis-account`
=> Set keyring-backend in setup script

app/app.go
Skip validations:
- max change rate:
- new rate cannot be changed more than once within 24 hours
=> Fix min-commission upgrade [moneta-beta]

docker-compose.yml, docker/setup_and_run.sh, docker/setup_junod.sh, docker/test-user.env, readme.md
This:
- Adds a compose file, meaning the local docker build is cached, and exposes all relevant ports
- Changes the setup script so that if it runs inside of an already-built container, already executed parts are skipped
- Instructions are moved out of the readme and into GitBook (I've parked the relevant sections in a change request there until this is merged)
- A couple typos I intro'd to the readme fixed by their removal (lol)
Thanks to @albttx for making me consider the utility of a `docker-compose` file even for a single-service project.
This PR supercedes https://github.com/CosmosContracts/juno/pull/93
=> Add compose file and restructure docs

.github/workflows/docker.yml
Second try at #98 
TL;DR the other PR added PRs and tags, but we use the GitHub UI to tag releases. These are not considered tags, but ... you guessed it, releases. So the other PR will only pick up tags on a push event.
Note that although this adds releases, these are not prereleases, only `[published, created, edited]` events. One of the event types available is `prereleased`, so I don't know if we want that as well? Thoughts?
=> Add release trigger to docker build.

app/wasm_config.go
Should do what it says on the tin.
As discussed on TG, so we can quickly test on uni/astarte before signing off moneta release.
=> 10x the wasm compile cost in config

app/app.go
- To be included in cosmovisor backup
- and `junod unsafe-reset-all`
=> Move wasm into data dir

Dockerfile, docker/setup_junod.sh
Updates the dockerfile and build to mirror mainnet, including a configured block gas fee.
This is important for testing and benchmarking smart contracts and changes to fees config.
Extracted from unrelated changes made in #122
=> Update wasmvm and development block gas limit

app/app.go
A basic upgrade handler for `moneta-patch` - if there are migrations required to e.g. try and change existing contract addresses then we will need to change this.
Second question - we can remove the `moneta` upgrade handler now, right?
=> Add moneta-patch base upgrade handler

.github/workflows/docker.yml, .github/workflows/integration.yml, docker-compose.yml, docker/setup_junod.sh
Deploy a contract as part of the CI harness.
Currently uses `whoami` as DAODAO is private, and changes to various scripts were needed.
=> Add edge pr tag and CW test harness

.github/workflows/release.yml
Closes #107 but will likely require a bit of fiddling.
This can't be properly tested until post-merge, unfortunately. I think it's going to be a bit of a pain to get right
=> tooling: spike binary release action

.github/workflows/integration.yml
Just noticed this - think the sleep is redundant as docker compose build step is blocking
=> Remove sleep from CI step

.github/workflows/release.yml
~Okay, so didn't look like the last one ran when I coined a release. Trying to work out why now.~
EDIT 1: Huh, apparently it _did_, it just didn't show a damn thing in the UI.
EDIT 2: Okay, it worked and the binary seems to work on a linux machine I just threw it on. Interesting. The step still needs naming however. I think the lack of name might be why it's not showing in the UI, as it shows on this PR _once you've given it a name_.
~Have set this to build on PR just so I can see what is going on.~
=> Add name to upload binary step

app/app.go
Moneta patch was a zombie handler we didn't use, I _think_ this upgrade is consensus breaking, so we will need a handler.
=> moneta patch handler -> lupercalia handler

go.mod, go.sum
They've released a quick version 'cos some things were missed. We should be able to just use this with the upgrade handler we just merged - and we've not officially tagged a release yet, so no biggie.
I've told uni validators that we will be testing the upgrade hopefully next Tuesday or Weds, so should have more than enough time to get this in :)
=> Bump to wasmd 0.23.0

readme.md
Just noticed the quickstart is out of date, so updated with the current docker-compose cmd.
=> Update README to reflect v2.3.0 quickstart cmd

docker/setup_junod.sh
Some users have reported Keplr issues even with `no-legacy-stdTx` set, and our team has encountered the same. It looks like it's simply a case of needing the REST server enabled, so makes sense to bundle it in with CORS config.
This PR is a placeholder so a container gets built that I can test locally.
=> Attempt to fix local REST server issues

go.mod, go.sum
Updates our wasmd version to the pre-release `wasmd@v0.27.0-junity.0` tag which has the fixes we need.
A note on the naming:
> unity &gt; rc, so [we] need to go up in the alphabet to J(uno) Unity
=> Bump to wasmd version for unity

RELEASES.md, readme.md
Still a draft for now, but I think now these procedures are solidifying we should co-locate them with the code so that we can point to it.
This also marks the move to a different versioning system where we mainly only care about major version and patch, rather than using minor version to signal things.
=> Add RELEASES procedures to repo

app/app.go
Fix error 
```
failed to execute message; message index: 0: client: no handler exists for proposal type
```
reference: https://github.com/cosmos/gaia/blob/v6.0.4/app/app.go#L387
=> Fix gov ibc RouterKey

go.mod, go.sum
Looks like the update from rc3 to 0.27.0 is now available. We should upgrade.
=> Bump wasmd version to 0.27.0

cmd/junod/main.go
This reverts commit e07087055b903aa721596f9e4928780ab8e34a7f.
cosmos-sdk 0.45.2 introduces a _rollback command_ which includes tendermint rollback.
Currently, junod v6.0.0 has 2 rollback cmd
```
rollback                 rollback cosmos-sdk and tendermint state by one height
rollback                 rollback tendermint state by one height
```
=> Revert "Merge pull request #80"

.github/workflows/build_docker.yml, .github/workflows/docker.yml, .github/workflows/gov.yml, .github/workflows/gov_deploy.yml, .github/workflows/gov_submit.yml, .github/workflows/integration.yml
This:
- Updates the names of a bunch of CI so it's clearer what it does
- Adds a unity contract CI runner to ensure there are no regressions
- Adds a unity contract governance action to ensure there are no regressions in Juno gov routing to contracts
- Adds a separate docker build _but not push_ step for PRs only (to sense check builds succeed)
=> Rename build steps and spike unity prop and gov/sudo testing CI step

app/app.go
As per the IBC go docs https://github.com/cosmos/ibc-go/blob/main/docs/migrations/v2-to-v3.md
I think I missed these in the enabling IBC Host PR, which means we _may_ need this to stop uni falling over.
If I'm wrong, let me know.
=> Add store types

.github/workflows/gov_deploy.yml, .github/workflows/gov_submit.yml, .github/workflows/integration.yml, .github/workflows/release.yml
Looks like the diagnosis of #207 could have gone much faster if we had the logs... trying 
https://github.com/jwalton/gh-docker-logs
(Re-introduced the failure to test)
@faddat I bet this would have saved quite a bit of time:
=> Add dump docker (on failure) to CI

app/app.go
- Fix `junod init ...` does not add `interchainaccounts` section to genesis
- Add to cli `junod q interchain-accounts`
=> Add ICA ModuleBasic

docker-compose.yml
To harmonize the `docker run` and `docker compose` approaches as well as to stay consistent with the "CosmWasm by Dummies"  series.
=> docker compose now denominates the STAKE_TOKEN in ujunox

go.mod, go.sum
This pull request simply updates ledger-go to v0.9.3 which adds support for Ledger Nano S+.
The same was done in Cosmos Hub a little while back: https://github.com/cosmos/gaia/commit/0420982086799cfad795f1ce271446002b9e5258
The ledger-go v0.9.3 release can be found here to see the changes: https://github.com/cosmos/ledger-go/releases/tag/v0.9.3
=> Added support for ledger nano s+

readme.md
This restructures the repo readme to:
- offer a more conscise piece of copy aimed at developers and validators
- remove pre-network genesis info about Juno
- remove params-based info about the chain & state that can change over time
- remove marketing-style copy
=> Restructure readme

cmd/junod/root.go
the configuration can be changed in `.juno/config/app.toml`
```toml
iavl-cache-size = 781250
iavl-disable-fastnode = true
```
perhaps it should be added to release notes for next version
=> Set IAVL config

cmd/junod/genica.go
The messages in genica command are now out-of-date, since v11 has shipped.
This simply... does that.
To confirm - check the messages added in upgrade handler match the ones added here.
=> Update genica command

Dockerfile
- Use latest alpine based golang image
- Use sh just to standardized shells
- combine `RUN` instructions
- Use `entrypoint` to handle os signals
=> fix(Dockerfile): latest alpine, use sh, combine run

app/app.go, app/export.go, app/keepers/keepers.go, app/keepers/keys.go, app/modules.go, app/upgrades/types.go, app/upgrades/v10/constants.go, app/upgrades/v10/upgrades.go, app/upgrades/v11/constants.go, app/upgrades/v11/upgrades.go
Closes https://github.com/CosmosContracts/juno/issues/245
I'm a bit unsure about upgrade handlers cause in existing `app.go` there is upgrade name check for  `"multiverse"` but there are two upgrades (v10 and v11), so not sure which one is which.
=> app.go refactor: Move keepers init, modules init and modularise upgrade handlers

cmd/junod/root.go, cmd/junod/tendermint.go
Is there a better way to reset application.db and wasm?  For example by extending into the "tendermint" reset-state command?
=> Reset application.db and  wasm

go.mod, go.sum
This PR brings us to the current version of github.com/cosmos/ledger-cosmos-go, which avoids the unmaintained dependency cosmos/ledger-go.
* https://github.com/cosmos/cosmos-sdk/issues/14007
=> use latest ledger, avoiding an unmaintained library

cmd/junod/cmd/resets.go, cmd/junod/cmd/root.go
This cleans up the main root command
```
junod reset-app
junod reset-wasm
```
Moved to its own sub-cmd
```
junod reset app
junod reset wasm
```
=> chore: Move reset-* commands to a subcmd (less rootCmd spam)

x/oracle/abci_test.go, x/oracle/keeper/history_test.go
1. Adds price history test for when we have multiple denominations (one denom is prefix of another also covered), to make sure that multiple denom entries does not interfere with each other.
2. Adds price history test for when price is queried for denom which hasn't been stored yet.
3. Adds abci tests for EndBlocker to see if price is correctly stored after validator vote period is over.
To discuss:
1. `getHistoryEntryBetweenTime()` returns `[]types.PriceHistoryEntry(nil)` instead of `[]types.PriceHistoryEntry{}` when the denom does not have stored prices. Is it expected or should be changed?
2. `GetArithmetricTWAP()` throws errror `no values in range` when there is no price entry for given denom before `startTime` becuase the first and last price entry is fetched using …
=> Oracle tests: multiple denom, denom with no entries; endBlocker tests

x/oracle/keeper/grpc_query_test.go
TWAP now returns a value in place of error when start time is before first entry, so now test reflects that
=> Update test for TWAP when startTime before first entry

app/upgrades/v12/upgrades.go
ICA module InitModule issue
This was originally done in v8.0.0 upgrade [v8 upgrade handler](https://github.com/CosmosContracts/juno/blob/v8.0.0/app/app.go#L835-L841) 
which originally added the controller & host, controller was just disabled (I thought it had not been added at all)
All we needed to do was update the params of both (enable controller, add more Msgs to Host)
---
roll back to block XXX500
fix ICA upgrade
if doesnt work, remove GlobalFee?
if doesnt work, FeeShare / Oracle?
=> Fix v12 Upgrade Handler

app/app.go, app/openapiconsole/console.go, app/openapiconsole/index.tpl, go.mod, go.sum
Riffing on Reece's very cool work to tune up the openapi 
console, this PR moves that into juno so that there's no 
longer any need to import anything from ignite, land of 
consensus rugging
=> Openapi without ignite

app/keepers/keepers.go, x/feeshare/README.md, x/feeshare/client/cli/tx.go, x/feeshare/keeper/msg_server.go, x/feeshare/keeper/msg_server_test.go, x/feeshare/spec/00_register.md, x/feeshare/spec/00_update.md, x/feeshare/types/errors.go
**note** backport to `reece/v13-part1` branch (later to be renamed `release/v13.0.x`
If there is a contract which is made to not be migrated or currently under the rule of a contract (ex: a dao) tthis allows it to register itself without requiring wasmbindings
(also adds vote query for incentivized voting with cosmwasm contracts)
**Idea:**
- DAO creates subDao & is the admin. The SubDAO can be registered and have the funds sent to itself for 50% of fees to the treasury
- Factory creates subContract, but there is no admin. Since Factory is a wasm contract, the contract can be registered to itself to collect fees
**Downside:**
- taxes? but a contract isn't really a business & this is for a small % of contracts
- once registered, this contract can not be changed unless we add wasmbindings. …
=> feat(x/feeshare): Allow registering factory contracts

.github/workflows/push-docker-images.yml
- linting is fixed in another PR
- e2e is being replaced with interchain test in another PR
Adds the v prefix to the CI - currently v13 is only 13.0.0 in ghcr. This on next tag will make it v13.0.1
Removes old e2e init chain test
I am putting the patch for this in my 597 v14 branch for main
---
Also if someone can delete https://github.com/CosmosContracts/juno/pkgs/container/juno/78312768?tag=reece-initial-v14 from the main juno that would be great :heart:
=> [v13] fix(docker): Adds v prefix (ex: v13.0.1)

cmd/junod/cmd/forceprune.go, go.mod, go.sum
Once Skip has a CometBFT fork we can switch to that. Non state breaking so we can get in after we launch on Uni if needed
This is the last SDK v45 release. **If users have issues with state sync, they MUST be on go.1.19+ to fix it**
=> [v14]: SDK v45.15 + CometBFT

go.mod, go.sum
This PR enables new token factory features on Juno. 
When going through #615, I made a flub, and this corrects my flub.
(I thought I'd updated the token factory version, but I hadn't)
=> chore(version) Use new token factory features

go.mod, go.sum
- I added a replace statement to replace vanilla cometbft with mev-cometbft 💯
=> include mev-cometbft instead of tendermint

go.mod, go.sum
We fixed a small number of bugs and code inefficiencies in advance of the upcoming chain-wide upgrade
=> (chore): bump mev-tendermint version

cmd/junod/cmd/root.go, cmd/junod/cmd/server_configs.go, go.mod
**Merges into v15-initial branch**
- Pulls out the `server.InterceptConfigsPreRunHandler` function into its own file
- Adds `blockTimeout` and force set it with `config.Consensus.TimeoutCommit` any time the junod command is run
- Adds the wasmconfig to increase gas queries to the config for all
```bash
CHAIN_ID="local-1" HOME_DIR="~/.juno1" TIMEOUT_COMMIT="100ms" CLEAN=true sh scripts/test_node.sh
```
Even with 100ms set as your config.toml, it still uses the set 3 seconds.
---
SDK v46/47 fix this by allowing direct modification of the tendermint config. This is why it has to be "soft forked" into a single file. 
Other chains which have implemented this feature already hard forked the SDK. Would rather not
=> [v15] Forced Faster Block Times (3 seconds)

go.mod, go.sum
This release provides a QoL improvement for validators by suppressing warning messages that arise when a validator has a partially configured mev-tendermint
https://github.com/skip-mev/mev-cometbft/releases/tag/v0.34.27-mev.18
=> (chore): bump mev-tendermint to v0.34.27-mev.18

go.mod, go.sum
Updating wasmvm to the latest version. Child's stuff.
=> chore: bump wasmvm

app/keepers/keepers.go
I believe it will be beneficial to Juno to add another allowed Stargate query.
See this query that we're talking about:
https://github.com/cosmos/cosmos-sdk/blob/v0.45.15/proto/cosmos/distribution/v1beta1/query.proto#L37-L41
With this addition, we'll see more programmatic claiming and staking of native tokens. Actually, this Twitter thread details how we can actually just delegate instead of the two-step claim-and-delegate flow we're accustomed to:
https://twitter.com/larry0x/status/1621959355221348352
I believe exposing this query doesn't introduce security concerns, and will help delegation UX if we do.
As an example, check this out… Here's my account with native balance and some tokens that need to be claimed.
Then (without claiming) I sent a `delegate` command for 31 JUNO, which can …
=> Add allowed Stargate query: distribution `DelegationRewards`

app/keepers/keepers.go, x/feeshare/keeper/keeper.go, x/feeshare/keeper/msg_server.go
In its current state, a gov admin'ed contract/DAO can not be self registered.
With this, if the admin of said contract is the gov module (ex: Core-1 subdao) it can now be registered to itself for feeshare income.
This is a very minor logic change
```go
govAddress := k.accountKeeper.GetModuleAddress(govtypes.ModuleName).String()
contractInfo.Admin == govAddress {
return true; // allow self register as a 'factory' contract
}
```
---
Tested manually, will add ictest after we get in the x/tokenfactory PR with IC changes
Trying to withdraw to another addr
Correctly withdrawing to itself
=> [v15] FeeShare register of governance admin contracts

.github/workflows/build_docker.yml, .github/workflows/interchaintest-E2E.yml, Makefile, app/app.go, app/keepers/keepers.go, app/keepers/keys.go, app/modules.go, app/upgrades/v13/upgrades.go, go.mod, go.sum, interchaintest/go.mod, interchaintest/ibc_transfer_test.go, scripts/hermes/transfer.sh, scripts/test_node.sh
Trying to narrow down where the issue lies for IBC not ack'ing
- Removes Ibchooks
- removes PFM
^ This fixes the channel-id not found error. But the packet is still not acked.
=> Fix v47 IBC test

go.mod, go.sum
Should be tagged v14.1.1. Do not use on testnet without cleaning wasm cache from v14.1.0 upgrade
Currently running on mine & dimis mainnet nodes
=> [v14] IBC Bump

app/keepers/keepers.go, x/ibchooks/wasm_hook.go
This is required for #660 and is the original proper way to do it.
I missed it during the v47 upgrade initial (since it works just fine without) except for upgrades to execute on a contract
PermissionedKeeper is required to get access to
=> Use PermissionedKeeper for ContractKeeper

interchaintest/chain_upgrade_test.go
A lot of the code can be abstracted so the test is easier to add new logic checks too & tear down. Overall just cleaner
- abstract away building the chain (with v47 params
- `SubmitUpgradeProposal` builds and submits the new v47 upgrade prop
- `ValidatorVoting` votes and gets prepped for halting
- `UpgradeNodes` upgrades at halted height and restarts nodes
=> [v17] Refactor ICTest e2e upgrades

app/app.go
Due to how `for` loop works, if many upgrade plans are specified, the store upgrades are taken from the last one on the list, not the one matched by the upgrade name. To fix this, the copy of the object is made, before taking the pointer.
=> fix: Fix pointer to store upgrades inside loop

app/ante.go, app/app.go
Due to usage of TFM & PFM + IBCHooks, IBC packets are much larger than the past. With this, more complex transfers are costing more and validators are not pushing through the packets except when done manually with fees.
- Increase gas limit from 1m to 2m temporarily 
- [Add MsgChannelOpen* messages to bypass per relayer request](https://discord.com/channels/816256689078403103/876537608438710382/1140938140350152755)
=> feat!: More global fee bypasses

x/globalfee/ante/fee.go, x/globalfee/ante/fee_utils.go
I have seen a lot of developers confused by the CLI fee message (all of cosmos, not just Juno). This makes it prettier so it's easier to understand
---
not enough
not accepted
none input at all but one is required
=> Prettier GlobalFee fees errors

x/globalfee/module.go, x/globalfee/types/codec.go
I missed this in the v16 upgrade oops :( - Adds so Gov can actually UpdateParams (Found thanks to setting up the x/clock module)
I need to write e2e test for all UpdateParams to confirm our custom messages work, not just the MsgServer
=> fix!: RegisterMsgServer for x/GlobalFee

app/keepers/keepers.go, x/burn/burner.go, x/mint/keeper/keeper.go, x/mint/simulation/genesis_test.go, x/tokenfactory/keeper/admins_test.go, x/tokenfactory/keeper/msg_server_test.go
this pr is targeting reece branch
- This way the bank.totalSupply will always be right
- By reducing target supply, we reduce also the maxSupply and we shorten the halving date
maxSupply is actually reduced way more than the burned coins, because maxsupply is calculated dynamically at each 1 year epoch based on inflation schedule
this table estimates how much the max supply will be impacted for a burn in each phase schedule
|  Year | Burn Amount   | Effective Max Supply reduction   |
|---|---|---|
|  2 | 1 JUNO | 2.04 JUNO  |   
| 3  | 1 JUNO |  1.70 JUNO |   
| 4  | 1 JUNO |  1.54 JUNO |
| 5 | 1 JUNO | 1.41 JUNO |
| 6 | 1 JUNO | 1.31 JUNO |
| 7 | 1 JUNO | 1.22 JUNO | 
| 8 | 1 JUNO | 1.15 JUNO |
| 9 | 1 JUNO | 1.10 JUNO |
| 10 | 1 JUNO | 1.06 JUNO | 
| 11 | 1 JUNO | 1.03 JUNO |
| 12 | 1 …
=> reduce tokens in targetsupply when burning

go.mod, go.sum
Currently Juno nodes would run into the following error once in a while with node halting:
```
[90m12:54PM[0m [32mINF[0m executed block [36mheight=[0m9522889 [36mmodule=[0mstate [36mnum_invalid_txs=[0m0 [36mnum_valid_txs=[0m3 [36mserver=[0mnode
fatal error: concurrent map iteration and map write
goroutine 963386 [running]:
runtime.throw({0x27ef174?, 0x8?})
runtime/panic.go:992 +0x71 fp=0xc0a2e49fb0 sp=0xc0a2e49f80 pc=0x43f0b1
runtime.mapiternext(0xc0a2e4a0a0?)
```
The new IAVL patch that has been made fixes this, this change is non-state breaking.
A new minor version release once this is merged is recommended in order to fix concurrency problems in mainnet
=> Use IAVL v0.20.1 & Fix Concurrency issue on mainnet

go.mod, go.sum
backport of #826 (origin offer matt) -> v16 release branch
running on my testnet valiadtor & mainnet rpc nodes now
- golanglint failure is due to an updated lint check in the latest version, this is fixed in v17 but did not apply to v16 at the time. Leaving unchanged
=> bump cosmos iavl for v16.x

app/app.go, app/keepers/keepers.go, app/sim_test.go, app/test_helpers.go, app/wasm_config.go, cmd/junod/cmd/root.go, go.mod, go.sum, interchaintest/chain_upgrade_test.go, interchaintest/conformance/cosmwasm.go, interchaintest/go.mod, interchaintest/go.sum, x/cw-hooks/genesis.go, x/feeshare/integration_test.go, x/tokenfactory/keeper/migrator.go
- wasmd v0.43
- wasvm 1.4.0
- ibc-go v7.3.1
- pfm latest
- Upgrade test: validate CW works & does not panic after upgrade (cc: Chihuahua chain halt due to wasmer issue)
=> [v18] wasm 1.4/wasmd 43, ibc+pfm latest, cw upgrade validation

app/app.go, app/keepers/keepers.go, app/upgrades/testnet/v18.0.0-alpha.3/constants.go, app/upgrades/testnet/v18.0.0-alpha.3/upgrade_test.go, go.mod, go.sum, interchaintest/go.mod, interchaintest/go.sum
v1800alpha3 upgrade
issues in v0.43 and 0.44 have caused many issues on testnet. The CW team has retracted these too (of which we are on testnet with) and requires a state breaking change to v0.45
=> fix!: Bump wasmd to v0.45

RELEASES.md
Hi, reading the doc I found out a current discord link is down, so I figured I would correct it myself instead of opening an issue and requiring someone to open a PR.
I found out the new discord link in readme.md, so it should be permanent. All other discord links are working in the repo.
That's it, doesn't require testing or changelog entry.
=> chore: updating discord link in RELEASES.md

app/app.go, app/keepers/keepers.go, go.mod, go.sum, interchaintest/go.mod, interchaintest/go.sum
TODO: Fix upstream documentation
=> Use different wasm VMs for standalone and the LC

app/app.go, app/upgrades/testnet/v19.0.0-alpha.2/constants.go, app/upgrades/testnet/v19.0.0-alpha.2/upgrade_test.go, app/upgrades/v19/upgrades.go
Forgot to put clock params in the upgrade handler
testnet: v1900alpha2 upgrade
mainnet: backported same change from `v1900alpha2`
Will go live on testnet next week, confirm clock is good, then mainnet
=> fix(upgrade): clock params

.github/CODEOWNERS, SECURITY.md
Merge once v19 is live on mainnet (Feb 5th) incase I need to rush review any patch
=> chore: remove Frey, Jack, and Reece from code owners & security

.github/workflows/golangci-lint.yml, .golangci.yml, app/decorators/change_rate_decorator_test.go, app/openapiconsole/console.go, cmd/junod/cmd/genica.go, cmd/junod/cmd/resets.go, x/clock/client/cli/query.go, x/clock/keeper/clock.go, x/cw-hooks/client/cli/query.go, x/feepay/ante/fee_route.go, x/feepay/keeper/feepay.go, x/feeshare/ante/ante_test.go, x/globalfee/client/cli/query.go, x/globalfee/querier_test.go, x/mint/client/cli/query.go, x/tokenfactory/client/cli/query.go, x/tokenfactory/simulation/operations.go
Basically, start with stuff that's easy.
- **Bump golangci/golangci-lint-action from 3 to 4**
- **update lint action**
- **do the easy stuff first....**
replaces #966
=> bump: golang-ci-lint-action

.github/workflows/interchaintest-E2E.yml
Update Github actions to attempt failed interchaintest tests for max 2 times so that CI pass in case of flakiness.
=> ci: allow flaky interchaintest to rerun.

.github/workflows/interchaintest-E2E.yml, app/app.go, app/upgrades/testnet/v23.0.0-alpha.1/constants.go, app/upgrades/testnet/v23.0.0-alpha.1/upgrade_test.go, app/upgrades/v23/constants.go, app/upgrades/v23/upgrade_test.go, app/upgrades/v23/upgrades.go, app/upgrades/v23/vesting.go, interchaintest/chain_upgrade_test.go, x/tokenfactory/keeper/bankactions.go, x/tokenfactory/keeper/keeper.go, x/tokenfactory/types/errors.go
This upgrade includes:
- Version bumps
- cometbft from v0.37.6 to v0.37.8
- cosmos-sdk from v0.47.11 to v0.47.12
- async-icq from v7.0.0 to v7.1.1
- ibc-go from v7.4.0 to v7.6.0
- skip/pob from v1.0.4 to v1.0.5
- Fix of a wrongly created module account for skip/pob module, related to the recent tokenfactory break
- Migration to community pool of Dimi’s, Jake’s and Lobo’s leftover vesting amount (around 553,035 $JUNO total)
- Updates to tokenfactory module for better error handling
It has been tested using CI and locally, on a [fork of mainnet juno](https://github.com/kintsugi-tech/chain-replicator)
correctly recalling 178095000000 * 3 ujuno to the community pool.
=> upgrade handler for v23

.github/workflows/release.yml
`docker-compose` was removed. 
https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/
=> Fix release-binary action

.github/CODEOWNERS
Add kintsugi validator collaborator to codeowners, to streamline development on juno
=> Add kintsugi collaborator to codeowners

readme.md, scripts/README.md
Corrected "ecosystem" to "Ecosystem" for proper capitalization.
Updated "locations in x/" to "locations in x/ directory" for clarity.
=> Fixed capitalization and clarified directory reference.
